# Generated by Django 5.2.17 on 2026-09-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0028_ratelist_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexTarget',
        ),
    ]
